"""add House model and modify other models accordingly

Revision ID: cb7c16638ecc
Revises: 10db9caed2ad
Create Date: 2024-09-23 11:44:59.724781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7c16638ecc'
down_revision = '10db9caed2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('houses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('style', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('electricityDollars', sa.Float(), nullable=True),
    sa.Column('gasDollars', sa.Float(), nullable=True),
    sa.Column('electricityCo2Produced', sa.Float(), nullable=True),
    sa.Column('gasCo2Produced', sa.Float(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('electricityCost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gasCost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('gasCost')
        batch_op.drop_column('electricityCost')

    op.drop_table('houses')
    # ### end Alembic commands ###
